# Generated by Django 2.0.4 on 2018-04-26 06:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='location')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='name')),
                ('logo', models.CharField(default='', max_length=128, verbose_name='logo')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='uuid')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('title', models.CharField(default='', max_length=128, verbose_name='title')),
                ('starts_at', models.DateTimeField(null=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(null=True, verbose_name='ends at')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('image_list', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=None)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_parser.Company', verbose_name='company')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_parser.City', verbose_name='city')),
            ],
            options={
                'verbose_name': 'vacancy',
                'verbose_name_plural': 'vacancies',
            },
        ),
    ]
